update mysql.user set host = '%' where user='root';

-- MySQL Script generated by MySQL Workbench
-- Thu May 28 08:09:16 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WJDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WJDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WJDB` DEFAULT CHARACTER SET utf8 ;
USE `WJDB` ;

-- -----------------------------------------------------
-- Table `WJDB`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`users` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `uid` VARCHAR(45) NULL,
                                              `first_name` VARCHAR(45) NOT NULL,
                                              `last_name` VARCHAR(45) NULL,
                                              `email` VARCHAR(45) NOT NULL,
                                              `password` VARCHAR(45) NOT NULL,
                                              `gender` VARCHAR(6) NULL,
                                              `birthday` DATE NULL,
                                              `avatarurl` VARCHAR(255) NULL,
                                              PRIMARY KEY (`id`),
                                              UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
                                              UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                              UNIQUE INDEX `uid_UNIQUE` (`uid` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`exercisetypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`exercisetypes` (
                                                      `id` INT NOT NULL AUTO_INCREMENT,
                                                      `name` VARCHAR(45) NOT NULL,
                                                      PRIMARY KEY (`id`),
                                                      UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
                                                      UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`parameters` (
                                                   `id` INT NOT NULL AUTO_INCREMENT,
                                                   `name` VARCHAR(45) NOT NULL,
                                                   `measure_unit` VARCHAR(10) NOT NULL,
                                                   `result_type` INT NOT NULL DEFAULT 1,
                                                   `value` FLOAT NOT NULL DEFAULT 0,
                                                   PRIMARY KEY (`id`),
                                                   UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`exercises` (
                                                  `id` INT NOT NULL AUTO_INCREMENT,
                                                  `name` VARCHAR(45) NOT NULL,
                                                  `description` VARCHAR(255) NULL,
                                                  `type_id` INT NOT NULL,
                                                  PRIMARY KEY (`id`),
                                                  INDEX `fk_Exercises_ExerciseTypes1_idx` (`type_id` ASC) VISIBLE,
                                                  CONSTRAINT `fk_Exercises_ExerciseTypes1`
                                                      FOREIGN KEY (`type_id`)
                                                          REFERENCES `WJDB`.`exercisetypes` (`id`)
                                                          ON DELETE NO ACTION
                                                          ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`exercises_parameters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`exercises_parameters` (
                                                             `id` INT NOT NULL AUTO_INCREMENT,
                                                             `exercise_id` INT NOT NULL,
                                                             `parameter_id` INT NOT NULL,
                                                             PRIMARY KEY (`id`),
                                                             INDEX `fk_Exercises_Parameters_Exercises1_idx` (`exercise_id` ASC) VISIBLE,
                                                             INDEX `fk_Exercises_Parameters_Parameters1_idx` (`parameter_id` ASC) VISIBLE,
                                                             CONSTRAINT `fk_Exercises_Parameters_Exercises1`
                                                                 FOREIGN KEY (`exercise_id`)
                                                                     REFERENCES `WJDB`.`exercises` (`id`)
                                                                     ON DELETE NO ACTION
                                                                     ON UPDATE NO ACTION,
                                                             CONSTRAINT `fk_Exercises_Parameters_Parameters1`
                                                                 FOREIGN KEY (`parameter_id`)
                                                                     REFERENCES `WJDB`.`parameters` (`id`)
                                                                     ON DELETE NO ACTION
                                                                     ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`workouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`workouts` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `name` VARCHAR(45) NOT NULL,
                                                 `planned_time` VARCHAR(10) NOT NULL,
                                                 `weekdays_mask` INT NOT NULL DEFAULT 0,
                                                 PRIMARY KEY (`id`),
                                                 UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`workouts_exercises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`workouts_exercises` (
                                                           `id` INT NOT NULL AUTO_INCREMENT,
                                                           `workout_id` INT NOT NULL,
                                                           `exercise_id` INT NOT NULL,
                                                           PRIMARY KEY (`id`),
                                                           UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                           INDEX `fk_Workouts_Exercises_Workouts1_idx` (`workout_id` ASC) VISIBLE,
                                                           INDEX `fk_Workouts_Exercises_Exercises1_idx` (`exercise_id` ASC) VISIBLE,
                                                           CONSTRAINT `fk_Workouts_Exercises_Workouts1`
                                                               FOREIGN KEY (`workout_id`)
                                                                   REFERENCES `WJDB`.`workouts` (`id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION,
                                                           CONSTRAINT `fk_Workouts_Exercises_Exercises1`
                                                               FOREIGN KEY (`exercise_id`)
                                                                   REFERENCES `WJDB`.`exercises` (`id`)
                                                                   ON DELETE NO ACTION
                                                                   ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`userworkouts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`userworkouts` (
                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                     `comments` VARCHAR(255) NULL,
                                                     `user_id` INT NOT NULL,
                                                     `workout_id` INT NOT NULL,
                                                     PRIMARY KEY (`id`),
                                                     UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                     INDEX `fk_UserWorkouts_Users1_idx` (`user_id` ASC) VISIBLE,
                                                     INDEX `fk_UserWorkouts_Workouts1_idx` (`workout_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_UserWorkouts_Users1`
                                                         FOREIGN KEY (`user_id`)
                                                             REFERENCES `WJDB`.`users` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_UserWorkouts_Workouts1`
                                                         FOREIGN KEY (`workout_id`)
                                                             REFERENCES `WJDB`.`workouts` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`userworkouts_parametervalues`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`userworkouts_parametervalues` (
                                                                     `id` INT NOT NULL AUTO_INCREMENT,
                                                                     `userWorkout_id` INT NOT NULL,
                                                                     `parameter_id` INT NOT NULL,
                                                                     `value` INT NOT NULL,
                                                                     PRIMARY KEY (`id`),
                                                                     UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                                     INDEX `fk_UserWorkouts_ParameterValues_UserWorkouts1_idx` (`userWorkout_id` ASC) VISIBLE,
                                                                     INDEX `fk_UserWorkouts_ParameterValues_Parameters1_idx` (`parameter_id` ASC) VISIBLE,
                                                                     CONSTRAINT `fk_UserWorkouts_ParameterValues_UserWorkouts1`
                                                                         FOREIGN KEY (`userWorkout_id`)
                                                                             REFERENCES `WJDB`.`userworkouts` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION,
                                                                     CONSTRAINT `fk_UserWorkouts_ParameterValues_Parameters1`
                                                                         FOREIGN KEY (`parameter_id`)
                                                                             REFERENCES `WJDB`.`parameters` (`id`)
                                                                             ON DELETE NO ACTION
                                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`doneexercise`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`doneexercise` (
                                                     `id` INT NOT NULL,
                                                     `exercise_id` INT NOT NULL,
                                                     `user_id` INT NOT NULL,
                                                     `date` DATE NOT NULL,
                                                     PRIMARY KEY (`id`),
                                                     UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                     INDEX `fk_doneexercise_exercises1_idx` (`exercise_id` ASC) VISIBLE,
                                                     INDEX `fk_doneexercise_users1_idx` (`user_id` ASC) VISIBLE,
                                                     CONSTRAINT `fk_doneexercise_exercises1`
                                                         FOREIGN KEY (`exercise_id`)
                                                             REFERENCES `WJDB`.`exercises` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION,
                                                     CONSTRAINT `fk_doneexercise_users1`
                                                         FOREIGN KEY (`user_id`)
                                                             REFERENCES `WJDB`.`users` (`id`)
                                                             ON DELETE NO ACTION
                                                             ON UPDATE NO ACTION)
    ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WJDB`.`parameterresult`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `WJDB`.`parameterresult` (
                                                        `id` INT NOT NULL,
                                                        `done_exercise_id` INT NOT NULL,
                                                        `parameter_id` INT NOT NULL,
                                                        `value` FLOAT NOT NULL DEFAULT 0,
                                                        PRIMARY KEY (`id`),
                                                        UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
                                                        INDEX `fk_parameterresult_doneexercise1_idx` (`done_exercise_id` ASC) VISIBLE,
                                                        INDEX `fk_parameterresult_parameters1_idx` (`parameter_id` ASC) VISIBLE,
                                                        CONSTRAINT `fk_parameterresult_doneexercise1`
                                                            FOREIGN KEY (`done_exercise_id`)
                                                                REFERENCES `WJDB`.`doneexercise` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION,
                                                        CONSTRAINT `fk_parameterresult_parameters1`
                                                            FOREIGN KEY (`parameter_id`)
                                                                REFERENCES `WJDB`.`parameters` (`id`)
                                                                ON DELETE NO ACTION
                                                                ON UPDATE NO ACTION)
    ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
